### ISSUE TITLE
UF DAO Attack not labeled by Bots

### ISSUE THREAD

**Issue by Kayaba-Attribution** [NethermindEth/general-agents-module#58]
Hello All!

I am doing an attack investigation on the UF DAO Attack on 2023-01-11 22:13:24 (UTC) on Binance Smart Chain Mainnet. And I was instructed to create an issue here if the alerts did not identify the victim protocol [UF DAO] :)

The attacker used the constructor of the attack contract to execute all the txns on [this transaction](https://bscscan.com/tx/0x933d19d7d822e84e34ca47ac733226367fbee0d9c0c89d88d431c4f99629d77a)

Some of the alerts that appear on the Forta Explorer contain the UF contract addresses on the details:

Contract Decompilation error 0x0f1876fe31e6208f84b91497781b3d1f94aa03e29a6f9fcb8e28107f1c3920a9
Suspicious Contract Creation  0x5b78e333ae9c9c769c1840fee25dc9bb1c665bec4a86bd3c5f91e1d49137bc07

[0xf887a2dac0dd432997c970bce597a94ead4a8c25](https://explorer.forta.network/alerts?addresses[]=0xf887a2dac0dd432997c970bce597a94ead4a8c25) UFT
[0xca49ecf7e7bb9bbc9d1d295384663f6ba5c0e366](https://explorer.forta.network/alerts?addresses[]=0xca49ecf7e7bb9bbc9d1d295384663f6ba5c0e366) Shop
[0x2101e0f648a2b5517fd2c5d9618582e9de7a651a](https://explorer.forta.network/alerts?addresses[]=0x2101e0f648a2b5517fd2c5d9618582e9de7a651a) UF

Perhaps a way to showcase this is to make a call on all the addresses for a name or symbol and diplay the non-reverted results besides the address, another way would be to extract the name from the explorer.

Going more into this hack alert, a way to detect it would be to check the UF contract USDC balances before/after the execution and you would see a decrease of $-89,958 alerting a possible hack

Please let me know if you need more info, always happy to help!!

**Comment by Vxatz** [comment]
Hi @Kayaba-Attribution, thanks for bringing this up. The bot already performs `name` an `symbol` checks and also uses Bscscan API. The issue most probably lies in the bot performance while executed on the network.
